Handle failed Crowdstrike API authentication slightly more gracefully
CrowdStrike/falcon-scripts pull request #129
Opened 2023-01-16 04:06 UTC by danoost

This will just print out the API response as JSON if you couldn't get a token for `docker login`, rather than trying to log in using an empty string and getting a generic failure message.

2023-01-16 15:31 UTC, carlosmmatos requested changes
The rest looks good. I would just change the verbiage for the error message.

2023-01-16 15:31 UTC, carlosmmatos commented on bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
> +  die "While getting a Docker token using your Crowdstrike token: ${TOKEN_RESPONSE}"
```suggestion
  die "Unable to obtain a Docker token using your Crowdstrike token: ${TOKEN_RESPONSE}"
```

2023-01-17 01:56 UTC, carlosmmatos approved these changes

2023-01-17 01:56 UTC, merged

2023-01-18 16:16 UTC, falcon-pioupiou commented
@carlosmmatos we need to revert this change it breaks the script - the output of the api will ALWAYS have the errors string:
```
{
	"meta": {
		"query_time": 9.6e-8,
		"powered_by": "cwppcontainersecurityapi",
		"trace_id": "dd418306-REDACTED-ad4fec919bd5"
	},
	"resources": [
		{
			"token": "REDACTED"
		}
	],
	"errors": []
}
```

it will always die as errors will be always there:
```
if echo "$TOKEN_RESPONSE" | grep -qw "errors"; then
```