Add Kubernetes Pull Token for specific sensor_type
CrowdStrike/falcon-scripts pull request #201
Opened 2023-09-07 18:02 UTC by falcon-pioupiou

I've added the pull-token generation.

Design question: Line 399, I've added a new line break which make the script ending with a new line.
so it's nice for someone looking to get the image pull token

BUT for automation it force scripts to use `echo -n $()` to remove the new line break

I think it's better to keep the new line break => any comment on this ?

2023-09-08 12:14 UTC, carlosmmatos requested changes

2023-09-08 12:14 UTC, carlosmmatos commented on bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
> +                       -H 'User-Agent: crowdstrike-falcon-scripts/1.1.7' \
Don't change this - this is done on new releases.

2023-09-08 12:14 UTC, carlosmmatos commented on bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
> +
I would stray away from using base64 here. Not all *nix shells are built the same ;)

Perfect example is running this from my macbook - I would get `-w` options does not exist. I'm also not sure if its needed since we are just echoing out the username:password. 

And to answer your comment about introducing a newline, I would stray away from that as well.

2023-11-02 12:46 UTC, falcon-pioupiou commented on bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
> +                       -H 'User-Agent: crowdstrike-falcon-scripts/1.1.7' \
👍  done (reverted this update)

2023-11-02 12:46 UTC, falcon-pioupiou commented on bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
> +
updated to support base64 with and without `-w`

2023-11-02 13:58 UTC, carlosmmatos commented on bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
> +set -o pipefail
```suggestion
set -eo pipefail
```

2023-11-02 14:06 UTC, falcon-pioupiou commented on bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
> +set -o pipefail
I removed the `set -o pipefail` as it was for debugging purpose and I didn't tested extensively with that config.

2023-11-06 13:43 UTC, carlosmmatos requested changes
let me know what you think about the changes suggested

2023-11-06 21:37 UTC, falcon-pioupiou commented
Lgtm! printf is much more cleaner

2023-11-07 17:59 UTC, carlosmmatos approved these changes
lgtm

2023-11-07 18:15 UTC, merged