Amazon Linux 1 support
CrowdStrike/falcon-scripts pull request #52
Opened 2022-04-27 12:13 UTC by lapkritinis

Two changes are required - one to recognize the OS name and another to convert the Amazon Linux version to mapping recognized by the Falcon sensor.
Amazon has versions like 2018.03 for Amazon Linux 1

2022-04-27 16:51 UTC, redhatrises commented on bash/install/falcon-linux-install.sh
> +    elif [ "$os_name" = "Amazon" ] && [ "$version" -ge 2011 ] ; then
Can we check that the version is `2018` since that is the only sensor for Amazon Linux 1 that is currently supported?

2022-04-27 17:04 UTC, redhatrises requested changes

2022-04-27 17:04 UTC, redhatrises commented on bash/install/falcon-linux-install.sh
> +      echo "1"
Can you also fix the spacing here?

2022-04-27 17:50 UTC, namendez-ml commented on bash/install/falcon-linux-install.sh
> +    elif [ "$os_name" = "Amazon" ] && [ "$version" -ge 2011 ] ; then
I just installed the sensor in an instance with Amazon Linux AMI 2017.09 and it seems to be working just fine, are you sure 2018 is the only supported version? (I was just about to submit a PR for this issue too)

2022-04-27 18:24 UTC, redhatrises commented on bash/install/falcon-linux-install.sh
> +    elif [ "$os_name" = "Amazon" ] && [ "$version" -ge 2011 ] ; then
The latest versions of 2018 and 2017 are the only supported versions. That's correct.

2022-04-28 14:51 UTC, lapkritinis commented
I updated pull requests with -ge 2017

2022-04-28 17:22 UTC, merged